version: 0.2

phases:
  pre_build:
    commands:
      - echo "🔐 Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 529088268162.dkr.ecr.ap-southeast-1.amazonaws.com
      - echo "🔧 Fetching EKS auth token manually..."
      - export K8S_TOKEN=$(aws eks get-token --region ap-southeast-1 --cluster-name betterwellness-cluster | jq -r '.status.token')
      - echo "📄 Downloading EKS CA cert to /tmp..."
      - mkdir -p /tmp/kube
      - export CERT_FILE=/tmp/kube/eks-ca.crt
      - echo "📄 Extracting EKS CA cert from kubeconfig..."
      - aws eks describe-cluster --name betterwellness-cluster --region ap-southeast-1 --query "cluster.certificateAuthority.data" --output text | base64 -d > eks-ca.crt
      - export K8S_SERVER="https://71B4D5459E1A0319B69A9329EC6483E4.gr7.ap-southeast-1.eks.amazonaws.com"
      - export NAMESPACE=betterwellness-cluster
      - export REPOSITORY_URI=529088268162.dkr.ecr.ap-southeast-1.amazonaws.com/betterwellness/booking-service
      - export IMAGE_TAG=latest

  build:
    commands:
      - echo "🏗️ Build started on `date`"
      - echo "📦 Building the Docker image..."
      - docker build -t betterwellness/booking-service .
      - docker tag betterwellness/booking-service:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "📤 Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "✅ Build completed on `date`"
      - echo "🚀 Restarting Kubernetes deployment..."
      - echo "🔍 Verifying EKS access..."
      - echo "👤 Who am I?"
      - aws sts get-caller-identity
      - echo "🔧 Kubernetes config context:"
      - kubectl config current-context || echo "⚠️ No current context"
      - echo "🔍 Checking Kubernetes contexts..."
      - kubectl config get-contexts || echo "⚠️ No contexts found"
      - echo "🔄 Restarting deployment..."
      - echo "🚀 Restarting Kubernetes deployment..."
      - echo "🛠 Creating temporary kubeconfig manually..."
      - export KUBECONFIG=$(mktemp)
      - |
        - |
        cat <<EOF > $KUBECONFIG
        apiVersion: v1
        kind: Config
        clusters:
        - cluster:
            server: $K8S_SERVER
            certificate-authority: $CERT_FILE
          name: betterwellness-cluster
        contexts:
        - context:
            cluster: betterwellness-cluster
            user: betterwellness-user
          name: betterwellness-context
        current-context: betterwellness-context
        users:
        - name: betterwellness-user
          user:
            token: $K8S_TOKEN
        EOF

      - echo "🔄 Restarting deployment using custom kubeconfig..."
      - kubectl rollout restart deployment betterwellness-booking -n $NAMESPACE