apiVersion: batch/v1
kind: Job
metadata:
  name: rollout-restart-booking
spec:
  template:
    spec:
      serviceAccountName: deployer  # This SA must have permissions
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command: ["sh", "-c"]
          args:
            - kubectl rollout restart deployment betterwellness-booking
      restartPolicy: Never
